const GET_ALL = "GET_ALL";
const GET_ALL_FAILURE = "GET_ALL_FAILURE";
const GET_CATEGORIES = "GET_CATEGORIES";
const SEARCH_PROFESSIONALS = "SEARCH_PROFESSIONALS";
const GET_ALL_SUPPLIERS = "GET_ALL_SUPPLIERS";
const APPLY_FILTERS = "APPLY_FILTERS";
const REGISTER_USER = "REGISTER_USER";
const GET_OCUPATION_BY_NAME= "GET_OCUPATION_BY_NAME";

export {
  GET_OCUPATION_BY_NAME,
  REGISTER_USER,
  APPLY_FILTERS,
  GET_ALL_SUPPLIERS,
  SEARCH_PROFESSIONALS,
  GET_CATEGORIES,
  GET_ALL_FAILURE,
  GET_ALL,
};
